# ===================================================================
# PERFIL DE PRODUCCIÓN (PROD)
# ===================================================================
# Identifica el entorno de ejecución como producción para AppInfoProperties
app.info.environment=prod
# Nivel de logging restrictivo para producción, registrando solo advertencias y errores
logging.level.com.example=WARN
