# ===================================================================
# PERFIL DE DESARROLLO (DEV)
# ===================================================================
# Identifica el entorno de ejecución como desarrollo para AppInfoProperties
app.info.environment=dev
# Nivel de logging detallado para depuración en los paquetes de la aplicación
logging.level.com.example=DEBUG
